
interface data {
    placeholder: string,
    minInputLength: number,
}
export const options = ref<data>({
    placeholder: 'States of USA',
    minInputLength: 1,
})
export const listFiltered = ref<string[]>([])
export const list = ref<string[]>(['West Side Story - 1961',
    'Lawrence of Arabia - 1962',
    'Tom Jones - 1963',
    'My Fair Lady - 1964',
    'The Sound of Music - 1965',
    'A Man for All Seasons - 1966',
    'In the Heat of the Night - 1967',
    'Oliver! - 1968',
    'Midnight Cowboy - 1969',
    'Patton - 1970',
    'The French Connection - 1971',
    'The Godfather - 1972',
    'The Sting - 1973',
    'The Godfather Part II - 1974',
    'One Flew over the Cuckoo"s Nest - 1975',
    'Rocky - 1976',
    'Annie Hall - 1978',
    'The Deer Hunter - 1979',
    'Kramer vs. Kramer - 1980',
    'Ordinary People - 1981',
    'Chariots of Fire - 1982',
    'Gandhi - 1983',
    'Terms of Endearment - 1984',
    'Amadeus - 1985',
    'Out of Africa - 1986',
    'Platoon - 1987',
    'The Last Emperor - 1988',
    'Rain Man - 1989',
    'Driving Miss Daisy - 1990',
    'Dances With Wolves - 1991',
    'The Silence of the Lambs - 1992',
    'Unforgiven - 1993',
    'Schindler’s List - 1994',
    'Forrest Gump - 1995',
    'Braveheart - 1996',
    'The English Patient - 1997',
    'Titanic - 1998',
    'Shakespeare in Love - 1999',
    'American Beauty - 2000',
    'Gladiator - 2001',
    'A Beautiful Mind - 2002',
    'Chicago - 2003',
    'The Lord of the Rings: The Return of the King - 2004',
    'Million Dollar Baby - 2005',
    'Crash - 2005',
    'The Departed - 2006',
    'No Country for Old Men - 2007',
    'Slumdog Millionaire - 2008',
    'The Hurt Locker - 2009',
    'The King"s Speech - 2010',
    'The Artist - 2011',
    'Argo - 2012',
])
export const multiple = ref<string[]>(["Boston Celtics", "Dallas Mavericks", "Brooklyn Nets", "Houston Rockets", "New York Knicks", "Memphis Grizzlies", "Philadelphia 76ers", "New Orleans Hornets", "Toronto Raptors", "San Antonio Spurs", "Chicago Bulls", "Denver Nuggets", "Cleveland Cavaliers", "Minnesota Timberwolves", "Detroit Pistons", "Portland Trail Blazers", "Indiana Pacers", "Oklahoma City Thunder", "Milwaukee Bucks", "Utah Jazz", "Atlanta Hawks", "Golden State Warriors", "Charlotte Bobcats", "Los Angeles Clippers", "Miami Heat", "Los Angeles Lakers", "Orlando Magic", "Phoenix Suns", "Washington Wizards", "Sacramento Kings", "New Jersey Devils", "New York Islanders", "New York Rangers", "Philadelphia Flyers", "Pittsburgh Penguins", "Chicago Blackhawks", "Columbus Blue Jackets", "Detroit Red Wings", "Nashville Predators", "St. Louis Blues", "Boston Bruins", "Buffalo Sabres", "Montreal Canadiens", "Ottawa Senators", "Toronto Maple Leafs", "Calgary Flames", "Colorado Avalanche", "Edmonton Oilers", "Minnesota Wild", "Vancouver Canucks", "Carolina Hurricanes", "Florida Panthers", "Tampa Bay Lightning", "Washington Capitals", "Winnipeg Jets", "Anaheim Ducks", "Dallas Stars", "Los Angeles Kings", "Phoenix Coyotes", "San Jose Sharks"]
)
export const remote = ref<string[]>(['West Side Story',
    'Lawrence of Arabia',
    'Tom Jones',
    'My Fair Lady',
    'The Sound of Music',
    'A Man for All Seasons',
    'In the Heat of the Night',
    'Oliver!',
    'Midnight Cowboy',
    'Patton',
    'The French Connection',
    'The Godfather',
    'The Sting',
    'The Godfather Part II',
    'One Flew over the Cuckoo"s Nest',
    'Rocky',
    'Annie Hall',
    'The Deer Hunter',
    'Kramer vs. Kramer',
    'Ordinary People',
    'Chariots of Fire',
    'Gandhi',
    'Terms of Endearment',
    'Amadeus',
    'Out of Africa',
    'Platoon',
    'The Last Emperor',
    'Rain Man',
    'Driving Miss Daisy',
    'Dances With Wolves',
    'The Silence of the Lambs',
    'Unforgiven',
    'Schindler’s List',
    'Forrest Gump',
    'Braveheart',
    'The English Patient',
    'Titanic',
    'Shakespeare in Love',
    'American Beauty',
    'Gladiator',
    'A Beautiful Mind',
    'Chicago',
    'The Lord of the Rings: The Return of the King',
    'Million Dollar Baby',
    'Crash',
    'The Departed',
    'No Country for Old Men',
    'Slumdog Millionaire',
    'The Hurt Locker',
    'The King"s Speech',
    'The Artist',
    'Argo',

])

export function onInput(event: { items: string[] }) {

    listFiltered.value = event.items;
}
export function onBlur(event: { items: string[] }) {

    listFiltered.value = event.items;
}
onMounted(() => {
    listFiltered.value = list.value;
})